import {
    Controller,
    All,
    Req,
    Param,
    NotFoundException,
    UseInterceptors,
    Logger,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Request } from 'express';
import { MockEndpoint } from '../../entities/mock-endpoint.entity';
import { ChaosInterceptor } from '../../chaos/chaos.interceptor';

@Controller('mocks/:projectId')
@UseInterceptors(ChaosInterceptor) // Apply Chaos Engineering logic
export class MockController {
    private readonly logger = new Logger(MockController.name);

    constructor(
        @InjectRepository(MockEndpoint)
        private mockEndpointRepo: Repository<MockEndpoint>,
    ) { }

    @All('*')
    async handleMockRequest(
        @Param('projectId') projectId: string,
        @Req() req: Request,
    ) {
        const method = req.method.toUpperCase();

        // Extract the relative path. 
        // If URL is /mocks/123-abc/users/profile, we want /users/profile
        // req.path usually returns the full path, so we strip the prefix.
        const prefix = `/mocks/${projectId}`;
        const relativePath = req.path.replace(prefix, '') || '/';

        this.logger.debug(`Mock Request: ${method} ${relativePath} (Project: ${projectId})`);

        // 1. Find the matching endpoint
        // In a production version, we would use regex matching for params like /users/:id
        // For this MVP, we look for exact matches generated by the AI.
        const endpoint = await this.mockEndpointRepo.findOne({
            where: {
                projectId,
                method,
                path: relativePath,
            },
        });

        if (!endpoint) {
            this.logger.warn(`Endpoint not found: ${method} ${relativePath}`);
            throw new NotFoundException({
                error: 'Mock Endpoint Not Found',
                message: `The path ${method} ${relativePath} has not been generated yet. Try scanning your repo again.`,
            });
        }

        // 2. Return the stored JSON data
        return endpoint.responseData;
    }
}
